# Generated by Django 2.2 on 2024-07-22 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Taxi',
            fields=[
                ('taxi_id', models.AutoField(primary_key=True, serialize=False)),
                ('current_location', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], default='A', max_length=1)),
                ('earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('location_index', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=255)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('pickup_point', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], max_length=1)),
                ('drop_point', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], max_length=1)),
                ('pickup_time', models.DateTimeField()),
                ('drop_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('booking_time', models.TimeField(auto_now_add=True)),
                ('booking_date', models.DateField(auto_now_add=True)),
                ('fare_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.Customer')),
                ('taxi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.Taxi')),
            ],
        ),
    ]
